---
# This is for OAuth Authentication.
# It shouldn't be here in a public repository, but nobody cares here, lol.
client_id: '13534'
access_token: 'e700b3216a28e56e9fa0a8ed7e83335f'
redirect_uri: 'formstack.jream.com'
